# docker-compose.yml

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    build:
      context: ./src/backend
      dockerfile: backend_dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src/backend:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app-network

  celery_worker:
    build:
      context: ./src/backend
      dockerfile: backend_dockerfile
    command: celery -A tasks.celery worker --loglevel=info
    volumes:
      - ./src/backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: frontend_dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  solver_service:
    build:
      context: ./src/backend/solver_service
      dockerfile: solver_service.dockerfile
    # If you run a Flask server, it might default to port 5000
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - backend
      - redis
    environment:
      # If you need to pass tokens / environment variables
      - SUPABASE_URL="https://zddqnxesbhbvmdcyqpuw.supabase.co"
      - SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZHFueGVzYmhidm1kY3lxcHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5Mjc4MjIsImV4cCI6MjA0NzUwMzgyMn0.aBMh1r41BNHRKuT1UICK2Rr2Vq6EqptdTVymf4FqvrY"
      

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
