services:

  frontend:
    build:
      context: ./src/frontend
      dockerfile: frontend_dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - solver_service
    networks:
      - app-network

  solver_service:
    build:
      context: ./src/backend
      dockerfile: solver_service.dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G
    env_file:
      - .env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}

networks:
  app-network:
    driver: bridge
